use kalcite_mir::Program;
use std::{fs, path::Path};

#[derive(Debug)]
pub enum Error {
    Io(std::io::Error),
    NoScene,
    InvalidName,
}

impl From<std::io::Error> for Error {
    fn from(value: std::io::Error) -> Self {
        Self::Io(value)
    }
}

impl core::fmt::Display for Error {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Io(error) => write!(f, "{error}"),
            Self::NoScene => write!(f, "no @scene class found"),
            Self::InvalidName => write!(
                f,
                "TI program name must contain 1..=8 ASCII letters or digits"
            ),
        }
    }
}

/// Emit the experimental TI-83+/TI-84+ Z80 project layout.
///
/// The emitted `main.z80` is intentionally a small launcher. It proves the
/// real calculator build/install path while the TI runtime is brought up;
/// Kalcite scene lowering is not enabled for this profile yet.
pub fn emit_project(program: &Program, app_name: &str, root: &Path) -> Result<(), Error> {
    let _scene = program.scene().ok_or(Error::NoScene)?;
    if !valid_name(app_name) {
        return Err(Error::InvalidName);
    }

    fs::create_dir_all(root)?;
    fs::write(root.join("main.z80"), assembly(app_name))?;
    fs::write(root.join("Makefile"), MAKEFILE)?;
    fs::write(root.join("README.md"), README)?;
    Ok(())
}

pub fn valid_name(name: &str) -> bool {
    !name.is_empty() && name.len() <= 8 && name.bytes().all(|byte| byte.is_ascii_alphanumeric())
}

fn assembly(name: &str) -> String {
    format!(
        "; Generated by Kalcite — experimental TI-83+/TI-84+ target\n\
         ; Build with `make` (requires spasm-ng).\n\
         ; This bootstrap launcher validates the .8xp pipeline.\n\
         #define PROGRAM_NAME \"{name}\"\n\
         #include \"ti83plus.inc\"\n\n\
         .org userMem-2\n\
         .db t2ByteTok, tAsmCmp\n\n\
         bcall(_ClrLCDFull)\n\
         ld hl, banner\n\
         bcall(_PutS)\n\
         bcall(_GetKey)\n\
         bcall(_JForceCmdNoChar)\n\n\
         banner:\n\
         .db \"Kalcite TI\", 0\n\n\
         .end\n"
    )
}

const MAKEFILE: &str = r#"PROGRAM ?= KALCITE

all: $(PROGRAM).8xp

$(PROGRAM).8xp: main.z80

	spasm-ng -T main.z80 $@
"#;

const README: &str = r#"# Kalcite TI target (experimental)

This is a Z80 project for the TI-83 Plus and TI-84 Plus monochrome family.

```sh
make PROGRAM=KALCITE
```

The command uses [Spasm-ng](https://github.com/alberthdev/spasm-ng) to create
a real `.8xp` program that can be transferred with TI-Connect CE or a link
tool. It is a bootstrap runtime: it displays a Kalcite TI launcher and proves
the assembler/package pipeline. Scene lowering, drawing and input mapping are
not implemented for this experimental profile yet.
"#;

#[cfg(test)]
mod tests {
    use super::valid_name;

    #[test]
    fn ti_names_are_eight_ascii_alphanumerics_at_most() {
        assert!(valid_name("KALCITE"));
        assert!(valid_name("GAME84"));
        assert!(!valid_name("TOO_LONG9"));
        assert!(!valid_name("KALCITE!"));
    }
}
