[package]
name = "kalcite-cli"
version.workspace = true
edition = "2024"
license = "MIT"

[[bin]]
name = "kalcite"
path = "src/main.rs"

[dependencies]
kalcite-compiler = { path = "../kalcite-compiler" }
kalcite-linter = { path = "../kalcite-linter" }
kalcite-project = { path = "../kalcite-project" }
kalcite-object = { path = "../kalcite-object" }
kalcite-stdlib = { path = "../kalcite-stdlib" }
kalcite-scene = { path = "../kalcite-scene" }
kalcite-assets = { path = "../kalcite-assets" }
kalcite-package = { path = "../kalcite-package" }
kalcite-test-runner = { path = "../kalcite-test-runner" }
kalcite-input = { path = "../kalcite-input" }
kalcite-save = { path = "../kalcite-save" }
kalcite-backend-desktop = { path = "../kalcite-backend-desktop" }
