use kalcite_mir::Program;
use std::{fs, path::Path};

#[derive(Debug)]
pub enum Error {
    Io(std::io::Error),
    NoScene,
    Rust(kalcite_backend_rust::EmitError),
}
impl From<std::io::Error> for Error {
    fn from(value: std::io::Error) -> Self { Self::Io(value) }
}
impl core::fmt::Display for Error {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Io(e) => write!(f, "{e}"),
            Self::NoScene => write!(f, "no @scene class found"),
            Self::Rust(e) => write!(f, "{e}"),
        }
    }
}

/// Emit a native desktop development runner.
///
/// The game still renders into the same 320x240 RGB565 logical framebuffer
/// used by the NumWorks backend. The host runner only presents that buffer in
/// a resizable native window using nearest-neighbour integer scaling.
pub fn emit_project(program: &Program, app_name: &str, root: &Path) -> Result<(), Error> {
    let scene = program.scene().ok_or(Error::NoScene)?;
    fs::create_dir_all(root.join("src"))?;
    fs::write(root.join("Cargo.toml"), cargo_manifest(app_name))?;
    fs::write(root.join("src/platform.rs"), PLATFORM)?;
    fs::write(root.join("src/runtime.rs"), RUNTIME)?;
    fs::write(root.join("src/stdlib.rs"), kalcite_stdlib::RUST_SOURCE)?;
    fs::write(
        root.join("src/game.rs"),
        kalcite_backend_rust::emit_game(program).map_err(Error::Rust)?,
    )?;
    let has_update = scene.functions.iter().any(|function| function.name == "update");
    let has_draw = scene.functions.iter().any(|function| function.name == "draw");
    let main = MAIN
        .replace("__SCENE__", &scene.name)
        .replace("__APP_NAME__", &escape_rust_string(app_name))
        .replace("__UPDATE_CALL__", if has_update { "game.update();" } else { "" })
        .replace("__DRAW_CALL__", if has_draw { "game.draw();" } else { "" });
    fs::write(root.join("src/main.rs"), main)?;
    Ok(())
}

fn escape_rust_string(value: &str) -> String {
    value.chars().flat_map(char::escape_default).collect()
}

fn cargo_manifest(name: &str) -> String {
    format!(r#"[package]
name = "kalcite-game-desktop"
version = "0.1.0"
edition = "2021"
description = "Generated by Kalcite: {name}"

[dependencies]
minifb = "0.27"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "symbols"

[workspace]
"#)
}

const RUNTIME: &str = include_str!("../../kalcite-runtime-core/src/pool.rs");

const PLATFORM: &str = r#"#![allow(dead_code)]
use core::ops::{Add, AddAssign, Sub, SubAssign};
use std::{
    fs::{self, File},
    path::PathBuf,
    io::{self, Write},
    sync::{atomic::{AtomicU32, AtomicU64, Ordering}, Mutex, OnceLock},
    thread,
    time::{Duration, Instant},
};

pub const WIDTH: usize = 320;
pub const HEIGHT: usize = 240;
pub const PIXELS: usize = WIDTH * HEIGHT;

static FRAMEBUFFER: OnceLock<Mutex<Box<[u16; PIXELS]>>> = OnceLock::new();
static KEYS: AtomicU64 = AtomicU64::new(0);
static START: OnceLock<Instant> = OnceLock::new();
static RANDOM_STATE: AtomicU32 = AtomicU32::new(0x4b1d_1234);

fn framebuffer() -> &'static Mutex<Box<[u16; PIXELS]>> {
    FRAMEBUFFER.get_or_init(|| Mutex::new(Box::new([0; PIXELS])))
}

#[derive(Clone, Copy, Default, Debug, PartialEq, Eq)]
pub struct Vec2fx { pub x: i16, pub y: i16 }
impl Vec2fx { pub const fn new(x: i16, y: i16) -> Self { Self { x, y } } }
impl Add for Vec2fx { type Output=Self; fn add(self,r:Self)->Self { Self{x:self.x+r.x,y:self.y+r.y} } }
impl AddAssign for Vec2fx { fn add_assign(&mut self,r:Self){self.x+=r.x;self.y+=r.y} }
impl Sub for Vec2fx { type Output=Self; fn sub(self,r:Self)->Self { Self{x:self.x-r.x,y:self.y-r.y} } }
impl SubAssign for Vec2fx { fn sub_assign(&mut self,r:Self){self.x-=r.x;self.y-=r.y} }

#[derive(Clone, Copy)] pub struct Color(pub u16);
#[allow(non_upper_case_globals)] impl Color {
    pub const Black:Self=Self(0x0000); pub const White:Self=Self(0xffff);
    pub const Red:Self=Self(0xf800); pub const Green:Self=Self(0x07e0);
    pub const Blue:Self=Self(0x001f); pub const Orange:Self=Self(0xfd20);
    pub const Yellow:Self=Self(0xffe0); pub const Cyan:Self=Self(0x07ff); pub const Gray:Self=Self(0x8410);
}

#[derive(Clone, Copy)] pub struct Key(pub u8);
#[allow(non_upper_case_globals)] impl Key {
    pub const Left:Self=Self(0); pub const Up:Self=Self(1); pub const Down:Self=Self(2);
    pub const Right:Self=Self(3); pub const Ok:Self=Self(4); pub const Back:Self=Self(5); pub const Home:Self=Self(6);
}

pub struct Input;
impl Input {
    #[inline]
    pub fn held(key: Key) -> bool {
        let bit = 1u64.checked_shl(key.0 as u32).unwrap_or(0);
        KEYS.load(Ordering::Relaxed) & bit != 0
    }
}

/// Host-only hook. Backends for calculators never expose this to game code.
pub fn host_set_key(key: Key, down: bool) {
    let bit = 1u64.checked_shl(key.0 as u32).unwrap_or(0);
    if down { KEYS.fetch_or(bit, Ordering::Relaxed); }
    else { KEYS.fetch_and(!bit, Ordering::Relaxed); }
}


pub struct System;
impl System {
    #[inline]
    pub fn millis() -> u32 {
        START.get_or_init(Instant::now).elapsed().as_millis() as u32
    }

    #[inline]
    pub fn sleep_ms(ms: u32) { thread::sleep(Duration::from_millis(ms as u64)); }
}

pub struct Hardware;
impl Hardware {
    pub fn is_numworks() -> bool { false }
    pub fn telemetry_supported() -> bool { true }
    pub fn battery_level() -> u32 { 100 }
    pub fn battery_mv() -> u32 { 5000 }
    pub fn charging() -> bool { false }
    pub fn usb_plugged() -> bool { false }
    pub fn backlight() -> u32 { 100 }
    pub fn random() -> u32 {
        let mut old=RANDOM_STATE.load(Ordering::Relaxed);
        loop {
            let mut x=old; x^=x<<13; x^=x>>17; x^=x<<5;
            match RANDOM_STATE.compare_exchange_weak(old,x,Ordering::Relaxed,Ordering::Relaxed) { Ok(_)=>return x, Err(v)=>old=v }
        }
    }
}

pub struct Storage;
impl Storage {
    pub fn supported() -> bool { true }

    fn path(name: &str) -> Option<PathBuf> {
        if name.is_empty() || name.len() > 48 { return None; }
        if !name.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'_' || b == b'-') { return None; }
        let root=PathBuf::from(".kalcite-saves");
        if fs::create_dir_all(&root).is_err() { return None; }
        Some(root.join(format!("{name}.kdoc")))
    }

    pub fn write_bytes(name: &str, bytes: &[u8]) -> bool {
        let Some(path)=Self::path(name) else { return false; };
        fs::write(path, bytes).is_ok()
    }

    pub fn read_into(name: &str, out: &mut [u8]) -> usize {
        let Some(path)=Self::path(name) else { return 0; };
        let Ok(bytes)=fs::read(path) else { return 0; };
        let n=core::cmp::min(bytes.len(),out.len()); out[..n].copy_from_slice(&bytes[..n]); n
    }

    pub fn write_text(name: &str, text: &str) -> bool { Self::write_bytes(name,text.as_bytes()) }

    pub fn exists(name: &str) -> bool {
        Self::path(name).is_some_and(|p| p.is_file())
    }

    pub fn size(name: &str) -> u32 {
        Self::path(name)
            .and_then(|p| fs::metadata(p).ok())
            .map(|m| m.len().min(u32::MAX as u64) as u32)
            .unwrap_or(0)
    }

    pub fn checksum(name: &str) -> u32 {
        let Some(path)=Self::path(name) else { return 0; };
        let Ok(bytes)=fs::read(path) else { return 0; };
        let mut h=0x811c9dc5u32;
        for b in bytes { h ^= b as u32; h=h.wrapping_mul(0x01000193); }
        h
    }

    pub fn remove(name: &str) -> bool {
        let Some(path)=Self::path(name) else { return false; };
        match fs::remove_file(path) { Ok(())=>true, Err(e)=>e.kind()==io::ErrorKind::NotFound }
    }

    // std does not expose portable filesystem free-space queries. These stay
    // zero on desktop unless a future host-storage backend adds such support.
    pub fn free_bytes() -> u32 { 0 }
    pub fn total_bytes() -> u32 { 0 }
}

pub struct Draw;
impl Draw {
    pub fn clear(c: Color) { framebuffer().lock().unwrap().fill(c.0); }
    pub fn rect(x:i16,y:i16,w:i16,h:i16,c:Color) {
        if w<=0 || h<=0 { return; }
        let x0=x.clamp(0,WIDTH as i16) as usize; let y0=y.clamp(0,HEIGHT as i16) as usize;
        let x1=(x+w).clamp(0,WIDTH as i16) as usize; let y1=(y+h).clamp(0,HEIGHT as i16) as usize;
        if x1<=x0 || y1<=y0 { return; }
        let mut fb=framebuffer().lock().unwrap();
        for yy in y0..y1 { let row=yy*WIDTH; for xx in x0..x1 { fb[row+xx]=c.0; } }
    }
    pub fn pixel_at(x:i16,y:i16)->u32 {
        if x<0 || y<0 || x>=WIDTH as i16 || y>=HEIGHT as i16 { return 0; }
        framebuffer().lock().unwrap()[y as usize*WIDTH+x as usize] as u32
    }
    pub fn text(text:&str,x:i16,y:i16,c:Color,bg:Color) {
        let mut px=x;
        for b in text.bytes() {
            if b==b'\n' { px=x; continue; }
            draw_char(b,px,y,c,bg); px+=6;
        }
    }
    pub fn number<T: Into<u64> + Copy>(value:T,x:i16,y:i16,c:Color,bg:Color) {
        let mut value:u64=value.into();
        let mut buf=[0u8;10]; let mut n=0usize;
        if value==0 { Self::text("0",x,y,c,bg); return; }
        while value>0 && n<buf.len() { buf[n]=b'0'+(value%10) as u8; value/=10; n+=1; }
        let mut px=x;
        while n>0 { n-=1; draw_char(buf[n],px,y,c,bg); px+=6; }
    }
}

fn glyph(c:u8)->[u8;7] {
    match c.to_ascii_uppercase() {
        b'A'=>[14,17,17,31,17,17,17], b'B'=>[30,17,17,30,17,17,30], b'C'=>[14,17,16,16,16,17,14],
        b'D'=>[30,17,17,17,17,17,30], b'E'=>[31,16,16,30,16,16,31], b'F'=>[31,16,16,30,16,16,16],
        b'G'=>[14,17,16,23,17,17,15], b'H'=>[17,17,17,31,17,17,17], b'I'=>[14,4,4,4,4,4,14],
        b'J'=>[7,2,2,2,2,18,12], b'K'=>[17,18,20,24,20,18,17], b'L'=>[16,16,16,16,16,16,31],
        b'M'=>[17,27,21,21,17,17,17], b'N'=>[17,25,21,19,17,17,17], b'O'=>[14,17,17,17,17,17,14],
        b'P'=>[30,17,17,30,16,16,16], b'Q'=>[14,17,17,17,21,18,13], b'R'=>[30,17,17,30,20,18,17],
        b'S'=>[15,16,16,14,1,1,30], b'T'=>[31,4,4,4,4,4,4], b'U'=>[17,17,17,17,17,17,14],
        b'V'=>[17,17,17,17,17,10,4], b'W'=>[17,17,17,21,21,21,10], b'X'=>[17,17,10,4,10,17,17],
        b'Y'=>[17,17,10,4,4,4,4], b'Z'=>[31,1,2,4,8,16,31],
        b'0'=>[14,17,19,21,25,17,14], b'1'=>[4,12,4,4,4,4,14], b'2'=>[14,17,1,2,4,8,31],
        b'3'=>[30,1,1,14,1,1,30], b'4'=>[2,6,10,18,31,2,2], b'5'=>[31,16,16,30,1,1,30],
        b'6'=>[14,16,16,30,17,17,14], b'7'=>[31,1,2,4,8,8,8], b'8'=>[14,17,17,14,17,17,14],
        b'9'=>[14,17,17,15,1,1,14], b'-'=>[0,0,0,31,0,0,0], b':'=>[0,4,4,0,4,4,0],
        b'/'=>[1,2,2,4,8,8,16], b'.'=>[0,0,0,0,0,4,4], b'%'=>[17,2,4,8,17,0,0],
        b'('=>[2,4,8,8,8,4,2], b')'=>[8,4,2,2,2,4,8], b'='=>[0,31,0,31,0,0,0],
        _=>[0,0,0,0,0,0,0],
    }
}
fn draw_char(ch:u8,x:i16,y:i16,c:Color,bg:Color) {
    let g=glyph(ch);
    rect_raw(x,y,6,8,bg);
    for (yy,row) in g.iter().enumerate() { for xx in 0..5 { if row & (1 << (4-xx)) != 0 { rect_raw(x+xx,y+yy as i16,1,1,c); } } }
}
fn rect_raw(x:i16,y:i16,w:i16,h:i16,c:Color) {
    if w<=0||h<=0{return;} let x0=x.clamp(0,WIDTH as i16) as usize; let y0=y.clamp(0,HEIGHT as i16) as usize;
    let x1=(x+w).clamp(0,WIDTH as i16) as usize; let y1=(y+h).clamp(0,HEIGHT as i16) as usize; if x1<=x0||y1<=y0{return;}
    let mut fb=framebuffer().lock().unwrap(); for yy in y0..y1 { let row=yy*WIDTH; for xx in x0..x1 { fb[row+xx]=c.0; } }
}

#[inline]
fn rgb565_to_xrgb8888(p: u16) -> u32 {
    let r=((p>>11)&31) as u32; let g=((p>>5)&63) as u32; let b=(p&31) as u32;
    let r=(r<<3)|(r>>2); let g=(g<<2)|(g>>4); let b=(b<<3)|(b>>2);
    (r<<16)|(g<<8)|b
}

pub fn host_copy_xrgb8888(dst: &mut [u32]) {
    assert_eq!(dst.len(), PIXELS);
    let fb=framebuffer().lock().unwrap();
    for (out, &pixel) in dst.iter_mut().zip(fb.iter()) { *out=rgb565_to_xrgb8888(pixel); }
}

pub fn frame_end() {}
pub fn save_ppm(path: &str) -> io::Result<()> {
    let fb=framebuffer().lock().unwrap();
    let mut f=File::create(path)?;
    write!(f,"P6\n{} {}\n255\n",WIDTH,HEIGHT)?;
    for &p in fb.iter() {
        let r=((p>>11)&31) as u8; let g=((p>>5)&63) as u8; let b=(p&31) as u8;
        f.write_all(&[(r<<3)|(r>>2),(g<<2)|(g>>4),(b<<3)|(b>>2)])?;
    }
    Ok(())
}
"#;

const MAIN: &str = r#"mod platform;
mod runtime;
mod stdlib;
#[allow(dead_code, non_camel_case_types, non_snake_case, unused_imports, unused_mut, unused_parens, unused_variables)]
mod game;

use minifb::{Key as HostKey, ScaleMode, Window, WindowOptions};
use std::{env, fs::File, io::Write, thread, time::{Duration, Instant}};

const APP_NAME: &str = "__APP_NAME__";
const DEFAULT_SCALE: usize = 3;
const DEFAULT_FPS: u32 = 60;

#[derive(Debug)]
struct Options {
    scale: usize,
    fps: u32,
    headless: bool,
    frames: u64,
    screenshot: String,
    profile: Option<String>,
}

fn options() -> Options {
    let mut out=Options{scale:DEFAULT_SCALE,fps:DEFAULT_FPS,headless:false,frames:180,screenshot:"kalcite-frame.ppm".into(),profile:None};
    let mut args=env::args().skip(1);
    while let Some(arg)=args.next() {
        match arg.as_str() {
            "--scale" => out.scale=args.next().and_then(|v|v.parse().ok()).unwrap_or(DEFAULT_SCALE).clamp(1,8),
            "--fps" => out.fps=args.next().and_then(|v|v.parse().ok()).unwrap_or(DEFAULT_FPS).clamp(1,240),
            "--headless" => out.headless=true,
            "--frames" => out.frames=args.next().and_then(|v|v.parse().ok()).unwrap_or(180),
            "--screenshot" => out.screenshot=args.next().unwrap_or_else(||"kalcite-frame.ppm".into()),
            "--profile" => out.profile=args.next(),
            "--help"|"-h" => {
                println!("{APP_NAME} (Kalcite desktop runner)\n  --scale N       integer window scale (1..8)\n  --fps N         target FPS (1..240)\n  --headless      run without a window\n  --frames N      frames in headless mode\n  --screenshot P  PPM output used by F12/headless mode\n  --profile P     write per-frame CSV timings\n\nKeys: arrows, Enter/Space=OK, Escape/Backspace=Back, H=Home, F12=screenshot, Q=quit");
                std::process::exit(0);
            }
            other => eprintln!("warning: unknown runner option `{other}`"),
        }
    }
    out
}

fn set_inputs(window: &Window) {
    use platform::{host_set_key, Key};
    host_set_key(Key::Left, window.is_key_down(HostKey::Left));
    host_set_key(Key::Up, window.is_key_down(HostKey::Up));
    host_set_key(Key::Down, window.is_key_down(HostKey::Down));
    host_set_key(Key::Right, window.is_key_down(HostKey::Right));
    host_set_key(Key::Ok, window.is_key_down(HostKey::Enter) || window.is_key_down(HostKey::Space));
    host_set_key(Key::Back, window.is_key_down(HostKey::Escape) || window.is_key_down(HostKey::Backspace));
    host_set_key(Key::Home, window.is_key_down(HostKey::H));
}

fn scale_nearest(src: &[u32], dst: &mut [u32], scale: usize) {
    let out_width=platform::WIDTH*scale;
    for y in 0..platform::HEIGHT {
        for sy in 0..scale {
            let dst_row=(y*scale+sy)*out_width;
            let src_row=y*platform::WIDTH;
            for x in 0..platform::WIDTH {
                let p=src[src_row+x];
                let start=dst_row+x*scale;
                dst[start..start+scale].fill(p);
            }
        }
    }
}

fn frame(game: &mut game::__SCENE__) {
    __UPDATE_CALL__
    __DRAW_CALL__
    platform::frame_end();
}


fn open_profile(opts: &Options) -> Option<File> {
    let path=opts.profile.as_ref()?;
    match File::create(path) {
        Ok(mut f) => { let _=writeln!(f,"frame,frame_us,fps"); Some(f) },
        Err(e) => { eprintln!("profile open failed for {path}: {e}"); None }
    }
}

fn write_profile(file: &mut Option<File>, frame_index:u64, start:Instant) {
    let us=start.elapsed().as_micros() as u64;
    let fps=if us>0 { 1_000_000.0/us as f64 } else { 0.0 };
    if let Some(f)=file.as_mut() { let _=writeln!(f,"{frame_index},{us},{fps:.3}"); }
}

fn run_headless(opts: &Options) {
    let mut game=game::__SCENE__::default();
    let mut profile=open_profile(opts);
    for i in 0..opts.frames { let started=Instant::now(); frame(&mut game); write_profile(&mut profile,i,started); }
    platform::save_ppm(&opts.screenshot).expect("failed to save screenshot");
    println!("Kalcite headless run complete: {} frames -> {}",opts.frames,opts.screenshot);
}

fn run_window(opts: &Options) {
    let width=platform::WIDTH*opts.scale;
    let height=platform::HEIGHT*opts.scale;
    let mut window=Window::new(
        &format!("{} — Kalcite",APP_NAME),
        width,
        height,
        WindowOptions { resize:false, scale_mode:ScaleMode::Stretch, ..WindowOptions::default() },
    ).expect("unable to create Kalcite desktop window");

    let mut game=game::__SCENE__::default();
    let mut logical=vec![0u32;platform::PIXELS];
    let mut presented=vec![0u32;width*height];
    let frame_time=Duration::from_secs_f64(1.0/opts.fps as f64);
    let mut next_frame=Instant::now();
    let mut screenshot_down=false;
    let mut profile=open_profile(opts);
    let mut frame_index=0u64;

    while window.is_open() && !window.is_key_down(HostKey::Q) {
        let started=Instant::now();
        set_inputs(&window);
        frame(&mut game);
        platform::host_copy_xrgb8888(&mut logical);
        scale_nearest(&logical,&mut presented,opts.scale);
        window.update_with_buffer(&presented,width,height).expect("failed to present framebuffer");

        let now_screenshot=window.is_key_down(HostKey::F12);
        if now_screenshot && !screenshot_down {
            match platform::save_ppm(&opts.screenshot) {
                Ok(())=>println!("saved {}",opts.screenshot),
                Err(e)=>eprintln!("screenshot failed: {e}"),
            }
        }
        screenshot_down=now_screenshot;
        write_profile(&mut profile,frame_index,started);
        frame_index+=1;

        next_frame+=frame_time;
        let now=Instant::now();
        if next_frame>now { thread::sleep(next_frame-now); }
        else if now.duration_since(next_frame)>frame_time*4 { next_frame=now; }
    }
}

fn main() {
    let opts=options();
    if opts.headless { run_headless(&opts); } else { run_window(&opts); }
}
"#;


#[cfg(test)]
mod generated_module_regression_tests {
    use super::*;

    #[test]
    fn generated_game_module_owns_codegen_lint_policy() {
        assert!(MAIN.contains("#[allow(dead_code, non_camel_case_types, non_snake_case, unused_imports, unused_mut, unused_parens, unused_variables)]\nmod game;"));
    }

    #[test]
    fn scene_lifecycle_hooks_are_template_gated() {
        assert!(MAIN.contains("__UPDATE_CALL__"));
        assert!(MAIN.contains("__DRAW_CALL__"));
    }

    #[test]
    fn desktop_runner_exposes_csv_profiling() {
        assert!(MAIN.contains("--profile"));
        assert!(MAIN.contains("frame,frame_us,fps"));
    }
}
